version: "3.9"

services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:80"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - backend

  backend:
    build: ./Back End
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
